// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLsnNkD1KUO7OHwrz12wlPyazuc1rfNxw',
    appId: '1:604077171637:android:783a2cff431c9c51382ffc',
    messagingSenderId: '604077171637',
    projectId: 'cobuild-ae278',
    storageBucket: 'cobuild-ae278.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWvuEJ7n6zSGW_PeJZIbRnQmEOYJDkoeU',
    appId: '1:604077171637:ios:a2305cf936bc4b3e382ffc',
    messagingSenderId: '604077171637',
    projectId: 'cobuild-ae278',
    storageBucket: 'cobuild-ae278.firebasestorage.app',
    androidClientId: '604077171637-2vnuhg8n1skias02cba2lp2flr6mvv4c.apps.googleusercontent.com',
    iosClientId: '604077171637-np06jsqpbd34s9f198org7j49h61t95k.apps.googleusercontent.com',
    iosBundleId: 'com.app.cobuild',
  );

}